fix: return required plugin
Plugins were required but not returned from the Array.prototype.map function,
therefore they were never actually loaded, causing the error:

    TypeError: Cannot call method 'init' of undefined